name: observatorio_geo_hist
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

scripts:
  get: fvm flutter pub get

  clean:
    $script: fvm flutter clean
    $after: fvm flutter pub get

  builder:
    $script: dart run build_runner watch --delete-conflicting-outputs

  run:
    $script: fvm flutter run -d chrome --web-renderer html

  test:
    $before: dart pub global run full_coverage
    $script: fvm flutter test --coverage

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  equatable: ^2.0.5
  cloud_firestore: ^5.4.4
  fpdart: ^1.1.0
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  get_it: ^8.0.0
  go_router: ^14.2.8
  carousel_slider: ^5.0.0
  url_launcher_web: ^2.3.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  collection: ^1.18.0
  flutter_markdown: ^0.7.5
  firebase_auth: ^5.4.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  firebase_storage: ^12.4.4
  file_picker: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/partners/

  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Dosis-Light.ttf
          weight: 300
        - asset: assets/fonts/Dosis-Medium.ttf
          weight: 400
        - asset: assets/fonts/Dosis-Regular.ttf
          weight: 500
        - asset: assets/fonts/Dosis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dosis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dosis-ExtraBold.ttf
          weight: 800
