// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-rKGRA0oZxtYhFPfEdT_LPWrdYfOPo8',
    appId: '1:415910016951:web:44597f77be6534a14e9a32',
    messagingSenderId: '415910016951',
    projectId: 'observatorio-geo-hist',
    authDomain: 'observatorio-geo-hist.firebaseapp.com',
    storageBucket: 'observatorio-geo-hist.appspot.com',
    measurementId: 'G-SXPB6RX0SV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfgmUiYcZCC5mOih-h0LM2-m664nL5K5E',
    appId: '1:415910016951:ios:d0d25de6411f04de4e9a32',
    messagingSenderId: '415910016951',
    projectId: 'observatorio-geo-hist',
    storageBucket: 'observatorio-geo-hist.appspot.com',
    iosBundleId: 'com.example.observatorioGeoHist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU-rKGRA0oZxtYhFPfEdT_LPWrdYfOPo8',
    appId: '1:415910016951:web:39f792aa18bdffa74e9a32',
    messagingSenderId: '415910016951',
    projectId: 'observatorio-geo-hist',
    authDomain: 'observatorio-geo-hist.firebaseapp.com',
    storageBucket: 'observatorio-geo-hist.appspot.com',
    measurementId: 'G-C6C45C3NZP',
  );
}
