name: Deploy Flutter Web to HostGator

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: |
        flutter pub get

    - name: Build Flutter Web app
      run: |
        flutter build web --release

    - name: Deploy to HostGator
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd /home/seu_usuario/public_html/curadoria && 
          git pull origin main &&
          rm -rf ./web/* &&
          cp -r /github/workspace/build/web/* ./web/
        "